
$image = wallpapers/green.jpg
$background = rgba(0e1513ff)

$image = wallpapers/green.jpg
$error = rgba(ffb4abff)

$image = wallpapers/green.jpg
$error_container = rgba(93000aff)

$image = wallpapers/green.jpg
$inverse_on_surface = rgba(2b322fff)

$image = wallpapers/green.jpg
$inverse_primary = rgba(0a6b5aff)

$image = wallpapers/green.jpg
$inverse_surface = rgba(dee4e0ff)

$image = wallpapers/green.jpg
$on_background = rgba(dee4e0ff)

$image = wallpapers/green.jpg
$on_error = rgba(690005ff)

$image = wallpapers/green.jpg
$on_error_container = rgba(ffdad6ff)

$image = wallpapers/green.jpg
$on_primary = rgba(00382dff)

$image = wallpapers/green.jpg
$on_primary_container = rgba(a1f2dcff)

$image = wallpapers/green.jpg
$on_primary_fixed = rgba(00201aff)

$image = wallpapers/green.jpg
$on_primary_fixed_variant = rgba(005143ff)

$image = wallpapers/green.jpg
$on_secondary = rgba(1d352eff)

$image = wallpapers/green.jpg
$on_secondary_container = rgba(cde8dfff)

$image = wallpapers/green.jpg
$on_secondary_fixed = rgba(07201aff)

$image = wallpapers/green.jpg
$on_secondary_fixed_variant = rgba(334b45ff)

$image = wallpapers/green.jpg
$on_surface = rgba(dee4e0ff)

$image = wallpapers/green.jpg
$on_surface_variant = rgba(bfc9c4ff)

$image = wallpapers/green.jpg
$on_tertiary = rgba(103447ff)

$image = wallpapers/green.jpg
$on_tertiary_container = rgba(c7e7ffff)

$image = wallpapers/green.jpg
$on_tertiary_fixed = rgba(001e2eff)

$image = wallpapers/green.jpg
$on_tertiary_fixed_variant = rgba(2a4a5fff)

$image = wallpapers/green.jpg
$outline = rgba(89938fff)

$image = wallpapers/green.jpg
$outline_variant = rgba(3f4945ff)

$image = wallpapers/green.jpg
$primary = rgba(85d6c0ff)

$image = wallpapers/green.jpg
$primary_container = rgba(005143ff)

$image = wallpapers/green.jpg
$primary_fixed = rgba(a1f2dcff)

$image = wallpapers/green.jpg
$primary_fixed_dim = rgba(85d6c0ff)

$image = wallpapers/green.jpg
$scrim = rgba(000000ff)

$image = wallpapers/green.jpg
$secondary = rgba(b1ccc3ff)

$image = wallpapers/green.jpg
$secondary_container = rgba(334b45ff)

$image = wallpapers/green.jpg
$secondary_fixed = rgba(cde8dfff)

$image = wallpapers/green.jpg
$secondary_fixed_dim = rgba(b1ccc3ff)

$image = wallpapers/green.jpg
$shadow = rgba(000000ff)

$image = wallpapers/green.jpg
$source_color = rgba(047c68ff)

$image = wallpapers/green.jpg
$surface = rgba(0e1513ff)

$image = wallpapers/green.jpg
$surface_bright = rgba(343b38ff)

$image = wallpapers/green.jpg
$surface_container = rgba(1b211fff)

$image = wallpapers/green.jpg
$surface_container_high = rgba(252b29ff)

$image = wallpapers/green.jpg
$surface_container_highest = rgba(303634ff)

$image = wallpapers/green.jpg
$surface_container_low = rgba(171d1bff)

$image = wallpapers/green.jpg
$surface_container_lowest = rgba(090f0eff)

$image = wallpapers/green.jpg
$surface_dim = rgba(0e1513ff)

$image = wallpapers/green.jpg
$surface_tint = rgba(85d6c0ff)

$image = wallpapers/green.jpg
$surface_variant = rgba(3f4945ff)

$image = wallpapers/green.jpg
$tertiary = rgba(aacbe3ff)

$image = wallpapers/green.jpg
$tertiary_container = rgba(2a4a5fff)

$image = wallpapers/green.jpg
$tertiary_fixed = rgba(c7e7ffff)

$image = wallpapers/green.jpg
$tertiary_fixed_dim = rgba(aacbe3ff)

